container:
  #connect_str: 
  #container_name: 
sql:
  #server: 
  #driver: 
  #username: 
  #password: 
  #database: 
data_dir:
  artifacts: artifacts
  raw_zip_data: artifacts/raw_zip_data/pneumonia-archive.zip
  raw_data: artifacts/raw_data